name: Hello

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to everyone
        run: echo "Hello Everyone..!!"

  Give_morning_greets:
    needs: say_hello
    runs-on: ubuntu-latest

    steps:
      - name: Say Good Monring 
        run: echo "Good Morning Everyone..!! have a nice day ahead"
